
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 18;
  public static final int decimal = 17;
  public static final int flechad = 6;
  public static final int coma = 15;
  public static final int concat = 9;
  public static final int conj = 2;
  public static final int or = 10;
  public static final int cadena2 = 19;
  public static final int guion = 14;
  public static final int ptcoma = 7;
  public static final int porcentajed = 8;
  public static final int EOF = 0;
  public static final int simbolo = 21;
  public static final int id = 20;
  public static final int error = 1;
  public static final int entero = 16;
  public static final int asterisco = 11;
  public static final int interrogacion = 13;
  public static final int llavec = 4;
  public static final int suma = 12;
  public static final int llavea = 3;
  public static final int dospuntos = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "llavea",
  "llavec",
  "dospuntos",
  "flechad",
  "ptcoma",
  "porcentajed",
  "concat",
  "or",
  "asterisco",
  "suma",
  "interrogacion",
  "guion",
  "coma",
  "entero",
  "decimal",
  "cadena",
  "cadena2",
  "id",
  "simbolo"
  };
}

